matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: '12'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    sudo: required
    language: node_js
    node_js: '12'
  - os: windows
    language: node_js
    node_js: '12'
before_script:
- export DISPLAY=:99.0
install:
- npm set progress=false
- npm install
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    npm run electron:linux
  elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
    npm run electron:mac
  else
    npm run electron:windows
  fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/win
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
branches:
  except:
    - /^untagged/
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^*-v[0-9]/
