matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: '12'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    sudo: required
    services: docker
    language: node_js
    node_js: '12'
before_script:
- export DISPLAY=:99.0
install:
- npm set progress=false
- |
  if [ $TRAVIS_OS_NAME = linux ]; then
    echo "2.7.15" > .python-version
    echo "3.7.1" > ./simulation_library/bindgen/.python-version
  fi
- npm install
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    npm run build:simlib:linux_docker
    npm run build:simlib:windows_docker
    ENVS=`env | grep -iE '^(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)([A-Z]|_)*=' | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
    docker run $ENVS --rm \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "npm run electron:win_lin"
  else
    npm run build:simlib:local
    npm run electron:mac
  fi
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
    - /^untagged/
    - /^v\\d+\\.\\d+\\.\\d+$/
deploy:
  provider: releases
  api_key:
    secure: fiJqEtqQ+yJwGzDHHANL7kmseliRn4tdT+91uZDOHx0gArxMmW/bUNUArpQEPGswd4yyZ5llGE2sdB63JKUHq/TDNfD20zgsZktshj44FvE/TKe1l2//QfoQT6x1Lc7JOcn2mPNIZarnntwY4ysxD6h+BAoRTtPIfw5ImdltIeTNhU+QnnqZVkO0CJxOw6T4GG7g+18UNufOX/HeCG1rSJgExJTEe5PoNU3xiPUBL7UzaYXehbeMHG6YjNDG27K5tTRownhx8NEUU3NWcNUQe710FDrOGs0I8bWpB4NXzfuiYplnHRaBpttGpYOa5PCvzY1d7SB+3xFl7HkwID4dV88HeWc5HAP5baoe7tQPnK8hTu10vS/yCSIQe1Io3OXmvQvjpbEdNnpG9MsBTsQxYJSQe1IersaEtrvtQuwHbc3W5YfLQv3lEZjRx14yez+/8SPTZip7KCuyh08PN15FOK0gfgUBpYszxfdfRUWWBV+66bA0QDwlRT+uVKCA1XNuLWS1T+5Ak6VvQfGN2/osgnDlUXRDp9q+S6O72Lf5bXhMiy0nW5bVOjDYtRvkxkm7g0/BWwZldZuL7JGxbRjtnXkFCs2Be0g9/p48KXbB2xXeei4zy34S7e3i2ljnFbZhyKLgyroZdKG+3B+V7BsJKMvpMF4pk3PtbtUjm3LQTw8=
  file_glob: true
  file:
    - "release/*.dmg"
    - "release/*.AppImage"
    - "release/*.exe"
  on:
    repo: gafert/RISC-V-Simulation
  skip_cleanup: 'true'
