/**
  * Generated by bindgen.py
  * Date: 2020-06-11 12:55:23.039824
  *
  * Usage in your own exported header file:
  * --------------------------------------------------
  * #include "bindings.h"
  *
  * extern "C" void example_function();
  *
  */

#include <cstdint>
#include "Vtestbench_Export.h"

#ifdef __cplusplus
extern "C" {
#endif

Vtestbench_EXPORT uint8_t *get_pointer_resetn();
Vtestbench_EXPORT uint8_t *get_pointer_trap();
Vtestbench_EXPORT uint8_t *get_pointer_mem_valid();
Vtestbench_EXPORT uint8_t *get_pointer_mem_ready();
Vtestbench_EXPORT uint8_t *get_pointer_mem_wstrb();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_la_read();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_la_write();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_la_wstrb();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__pcpi_valid();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__reg_sh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__pcpi_mul_wr();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__pcpi_mul_wait();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__pcpi_mul_ready();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__pcpi_int_wr();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_state();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_wordsize();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_do_prefetch();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_do_rinst();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_do_rdata();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_do_wdata();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_xfer();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__mem_done();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_lui();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_auipc();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_jal();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_jalr();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_beq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_bne();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_blt();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_bge();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_bltu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_bgeu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_lb();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_lh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_lw();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_lbu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_lhu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sb();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sw();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_addi();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_slti();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sltiu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_xori();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_ori();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_andi();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_slli();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_srli();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_srai();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_add();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sub();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sll();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_slt();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sltu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_xor();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_srl();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_sra();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_or();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_and();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_rdcycle();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_rdcycleh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_rdinstr();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_rdinstrh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_ecall_ebreak();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_getq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_setq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_retirq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_maskirq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_waitirq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_timer();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__instr_trap();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__decoded_rd();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__decoded_rs1();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__decoded_rs2();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__decoder_trigger();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__decoder_trigger_q();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__decoder_pseudo_trigger();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__decoder_pseudo_trigger_q();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__compressed_instr();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_lui_auipc_jal();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_lb_lh_lw_lbu_lhu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_slli_srli_srai();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_sb_sh_sw();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_sll_srl_sra();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_slti_blt_slt();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_sltiu_bltu_sltu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_beq_bne_blt_bge_bltu_bgeu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_lbu_lhu_lw();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_alu_reg_imm();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_alu_reg_reg();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__is_compare();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__dbg_next();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__launch_next_insn();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__cpu_state();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__set_mem_do_rinst();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__set_mem_do_rdata();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__set_mem_do_wdata();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_store();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_stalu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_branch();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_compr();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_is_lu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_is_lh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_is_lb();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__latched_rd();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__do_waitirq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__alu_out_0();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__alu_eq();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__alu_ltu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__alu_lts();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__cpuregs_write();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish();
Vtestbench_EXPORT uint32_t *get_pointer_resetn_cnt();
Vtestbench_EXPORT uint32_t *get_pointer_mem_addr();
Vtestbench_EXPORT uint32_t *get_pointer_mem_wdata();
Vtestbench_EXPORT uint32_t *get_pointer_mem_rdata();
Vtestbench_EXPORT uint32_t *get_pointer_x32();
Vtestbench_EXPORT uint32_t *get_pointer_next_x32();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__mem_la_wdata();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__pcpi_insn();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__reg_pc();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__reg_next_pc();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__reg_op1();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__reg_op2();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__reg_out();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__next_insn_opcode();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__dbg_insn_opcode();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__dbg_insn_addr();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__next_pc();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__timer();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__pcpi_mul_rd();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__pcpi_int_rd();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__mem_rdata_word();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__mem_rdata_q();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__mem_rdata_latched_noshuffle();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__decoded_imm();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__decoded_imm_j();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__q_insn_opcode();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__cached_insn_opcode();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__current_pc();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__alu_out();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__alu_out_q();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__cpuregs_wrdata();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__cpuregs_rs1();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__cpuregs_rs2();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__new_ascii_instr();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__dbg_ascii_instr();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__q_ascii_instr();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__cached_ascii_instr();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx();
Vtestbench_EXPORT unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt();
Vtestbench_EXPORT uint8_t *get_pointer_memory();
Vtestbench_EXPORT uint32_t *get_pointer_uut__DOT__cpuregs();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1();
Vtestbench_EXPORT uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2();

typedef void (*buffer_write_t)(int character);
Vtestbench_EXPORT void set_buffer_write_callback(buffer_write_t function);

#ifdef __cplusplus
}
#endif

