/**
  * Generated by bindgen.py
  * Date: 2020-04-24 22:43:25.453503
  * 
  * Usage in your own exported header file:
  * --------------------------------------------------
  * #include "bindings.h"
  * 
  * extern "C" void example_function();
  * 
  */

#include <cstdint>

#ifdef __cplusplus
extern "C" {
#endif

uint8_t *get_pointer_resetn();
uint8_t *get_pointer_trap();
uint8_t *get_pointer_mem_valid();
uint8_t *get_pointer_mem_ready();
uint8_t *get_pointer_mem_wstrb();
uint8_t *get_pointer_uut__DOT__mem_la_read();
uint8_t *get_pointer_uut__DOT__mem_la_write();
uint8_t *get_pointer_uut__DOT__mem_la_wstrb();
uint8_t *get_pointer_uut__DOT__pcpi_valid();
uint8_t *get_pointer_uut__DOT__reg_sh();
uint8_t *get_pointer_uut__DOT__pcpi_mul_wr();
uint8_t *get_pointer_uut__DOT__pcpi_mul_wait();
uint8_t *get_pointer_uut__DOT__pcpi_mul_ready();
uint8_t *get_pointer_uut__DOT__pcpi_int_wr();
uint8_t *get_pointer_uut__DOT__mem_state();
uint8_t *get_pointer_uut__DOT__mem_wordsize();
uint8_t *get_pointer_uut__DOT__mem_do_prefetch();
uint8_t *get_pointer_uut__DOT__mem_do_rinst();
uint8_t *get_pointer_uut__DOT__mem_do_rdata();
uint8_t *get_pointer_uut__DOT__mem_do_wdata();
uint8_t *get_pointer_uut__DOT__mem_xfer();
uint8_t *get_pointer_uut__DOT__mem_done();
uint8_t *get_pointer_uut__DOT__instr_lui();
uint8_t *get_pointer_uut__DOT__instr_auipc();
uint8_t *get_pointer_uut__DOT__instr_jal();
uint8_t *get_pointer_uut__DOT__instr_jalr();
uint8_t *get_pointer_uut__DOT__instr_beq();
uint8_t *get_pointer_uut__DOT__instr_bne();
uint8_t *get_pointer_uut__DOT__instr_blt();
uint8_t *get_pointer_uut__DOT__instr_bge();
uint8_t *get_pointer_uut__DOT__instr_bltu();
uint8_t *get_pointer_uut__DOT__instr_bgeu();
uint8_t *get_pointer_uut__DOT__instr_lb();
uint8_t *get_pointer_uut__DOT__instr_lh();
uint8_t *get_pointer_uut__DOT__instr_lw();
uint8_t *get_pointer_uut__DOT__instr_lbu();
uint8_t *get_pointer_uut__DOT__instr_lhu();
uint8_t *get_pointer_uut__DOT__instr_sb();
uint8_t *get_pointer_uut__DOT__instr_sh();
uint8_t *get_pointer_uut__DOT__instr_sw();
uint8_t *get_pointer_uut__DOT__instr_addi();
uint8_t *get_pointer_uut__DOT__instr_slti();
uint8_t *get_pointer_uut__DOT__instr_sltiu();
uint8_t *get_pointer_uut__DOT__instr_xori();
uint8_t *get_pointer_uut__DOT__instr_ori();
uint8_t *get_pointer_uut__DOT__instr_andi();
uint8_t *get_pointer_uut__DOT__instr_slli();
uint8_t *get_pointer_uut__DOT__instr_srli();
uint8_t *get_pointer_uut__DOT__instr_srai();
uint8_t *get_pointer_uut__DOT__instr_add();
uint8_t *get_pointer_uut__DOT__instr_sub();
uint8_t *get_pointer_uut__DOT__instr_sll();
uint8_t *get_pointer_uut__DOT__instr_slt();
uint8_t *get_pointer_uut__DOT__instr_sltu();
uint8_t *get_pointer_uut__DOT__instr_xor();
uint8_t *get_pointer_uut__DOT__instr_srl();
uint8_t *get_pointer_uut__DOT__instr_sra();
uint8_t *get_pointer_uut__DOT__instr_or();
uint8_t *get_pointer_uut__DOT__instr_and();
uint8_t *get_pointer_uut__DOT__instr_rdcycle();
uint8_t *get_pointer_uut__DOT__instr_rdcycleh();
uint8_t *get_pointer_uut__DOT__instr_rdinstr();
uint8_t *get_pointer_uut__DOT__instr_rdinstrh();
uint8_t *get_pointer_uut__DOT__instr_ecall_ebreak();
uint8_t *get_pointer_uut__DOT__instr_getq();
uint8_t *get_pointer_uut__DOT__instr_setq();
uint8_t *get_pointer_uut__DOT__instr_retirq();
uint8_t *get_pointer_uut__DOT__instr_maskirq();
uint8_t *get_pointer_uut__DOT__instr_waitirq();
uint8_t *get_pointer_uut__DOT__instr_timer();
uint8_t *get_pointer_uut__DOT__instr_trap();
uint8_t *get_pointer_uut__DOT__decoded_rd();
uint8_t *get_pointer_uut__DOT__decoded_rs1();
uint8_t *get_pointer_uut__DOT__decoded_rs2();
uint8_t *get_pointer_uut__DOT__decoder_trigger();
uint8_t *get_pointer_uut__DOT__decoder_trigger_q();
uint8_t *get_pointer_uut__DOT__decoder_pseudo_trigger();
uint8_t *get_pointer_uut__DOT__decoder_pseudo_trigger_q();
uint8_t *get_pointer_uut__DOT__compressed_instr();
uint8_t *get_pointer_uut__DOT__is_lui_auipc_jal();
uint8_t *get_pointer_uut__DOT__is_lb_lh_lw_lbu_lhu();
uint8_t *get_pointer_uut__DOT__is_slli_srli_srai();
uint8_t *get_pointer_uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi();
uint8_t *get_pointer_uut__DOT__is_sb_sh_sw();
uint8_t *get_pointer_uut__DOT__is_sll_srl_sra();
uint8_t *get_pointer_uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub();
uint8_t *get_pointer_uut__DOT__is_slti_blt_slt();
uint8_t *get_pointer_uut__DOT__is_sltiu_bltu_sltu();
uint8_t *get_pointer_uut__DOT__is_beq_bne_blt_bge_bltu_bgeu();
uint8_t *get_pointer_uut__DOT__is_lbu_lhu_lw();
uint8_t *get_pointer_uut__DOT__is_alu_reg_imm();
uint8_t *get_pointer_uut__DOT__is_alu_reg_reg();
uint8_t *get_pointer_uut__DOT__is_compare();
uint8_t *get_pointer_uut__DOT__cpu_state();
uint8_t *get_pointer_uut__DOT__set_mem_do_rinst();
uint8_t *get_pointer_uut__DOT__set_mem_do_rdata();
uint8_t *get_pointer_uut__DOT__set_mem_do_wdata();
uint8_t *get_pointer_uut__DOT__latched_store();
uint8_t *get_pointer_uut__DOT__latched_stalu();
uint8_t *get_pointer_uut__DOT__latched_branch();
uint8_t *get_pointer_uut__DOT__latched_compr();
uint8_t *get_pointer_uut__DOT__latched_is_lu();
uint8_t *get_pointer_uut__DOT__latched_is_lh();
uint8_t *get_pointer_uut__DOT__latched_is_lb();
uint8_t *get_pointer_uut__DOT__latched_rd();
uint8_t *get_pointer_uut__DOT__do_waitirq();
uint8_t *get_pointer_uut__DOT__alu_out_0();
uint8_t *get_pointer_uut__DOT__alu_eq();
uint8_t *get_pointer_uut__DOT__alu_ltu();
uint8_t *get_pointer_uut__DOT__alu_lts();
uint8_t *get_pointer_uut__DOT__cpuregs_write();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish();
uint32_t *get_pointer_resetn_cnt();
uint32_t *get_pointer_mem_addr();
uint32_t *get_pointer_mem_wdata();
uint32_t *get_pointer_mem_rdata();
uint32_t *get_pointer_x32();
uint32_t *get_pointer_next_x32();
uint32_t *get_pointer_uut__DOT__mem_la_wdata();
uint32_t *get_pointer_uut__DOT__pcpi_insn();
uint32_t *get_pointer_uut__DOT__reg_pc();
uint32_t *get_pointer_uut__DOT__reg_next_pc();
uint32_t *get_pointer_uut__DOT__reg_op1();
uint32_t *get_pointer_uut__DOT__reg_op2();
uint32_t *get_pointer_uut__DOT__reg_out();
uint32_t *get_pointer_uut__DOT__next_pc();
uint32_t *get_pointer_uut__DOT__timer();
uint32_t *get_pointer_uut__DOT__pcpi_mul_rd();
uint32_t *get_pointer_uut__DOT__pcpi_int_rd();
uint32_t *get_pointer_uut__DOT__mem_rdata_word();
uint32_t *get_pointer_uut__DOT__mem_rdata_q();
uint32_t *get_pointer_uut__DOT__mem_rdata_latched_noshuffle();
uint32_t *get_pointer_uut__DOT__decoded_imm();
uint32_t *get_pointer_uut__DOT__decoded_imm_j();
uint32_t *get_pointer_uut__DOT__current_pc();
uint32_t *get_pointer_uut__DOT__alu_out();
uint32_t *get_pointer_uut__DOT__alu_out_q();
uint32_t *get_pointer_uut__DOT__cpuregs_wrdata();
uint32_t *get_pointer_uut__DOT__cpuregs_rs1();
uint32_t *get_pointer_uut__DOT__cpuregs_rs2();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx();
unsigned long *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt();
uint8_t *get_pointer_memory();
uint32_t *get_pointer_uut__DOT__cpuregs();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1();
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2();

typedef void (*buffer_write_t)(int character);
void set_buffer_write_callback(buffer_write_t function);

#ifdef __cplusplus
}
#endif

