/**
  * Generated by bindgen.py
  * Date: 2020-06-11 12:55:23.040344
  *
  * Usage in your own cpp code:
  * --------------------------------------------------
  * #include "bindings.cc"
  *
  * Vtestbench *top;
  *
  * void example_function() {
  *     Verilated::commandArgs(0, (char **) "");
  *     top = new Vtestbench;
  * }
  *
  */

#include "bindings.h"
#include "Vtestbench.h"

extern Vtestbench *top;

/** Returns pointer of uint8_t */
uint8_t *get_pointer_resetn() { return (uint8_t*) &top->testbench__DOT__resetn; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_trap() { return (uint8_t*) &top->testbench__DOT__trap; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_mem_valid() { return (uint8_t*) &top->testbench__DOT__mem_valid; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_mem_ready() { return (uint8_t*) &top->testbench__DOT__mem_ready; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_mem_wstrb() { return (uint8_t*) &top->testbench__DOT__mem_wstrb; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_la_read() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_la_read; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_la_write() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_la_write; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_la_wstrb() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_la_wstrb; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__pcpi_valid() { return (uint8_t*) &top->testbench__DOT__uut__DOT__pcpi_valid; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__reg_sh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__reg_sh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__pcpi_mul_wr() { return (uint8_t*) &top->testbench__DOT__uut__DOT__pcpi_mul_wr; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__pcpi_mul_wait() { return (uint8_t*) &top->testbench__DOT__uut__DOT__pcpi_mul_wait; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__pcpi_mul_ready() { return (uint8_t*) &top->testbench__DOT__uut__DOT__pcpi_mul_ready; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__pcpi_int_wr() { return (uint8_t*) &top->testbench__DOT__uut__DOT__pcpi_int_wr; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_state() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_state; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_wordsize() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_wordsize; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_do_prefetch() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_do_prefetch; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_do_rinst() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_do_rinst; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_do_rdata() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_do_rdata; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_do_wdata() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_do_wdata; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_xfer() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_xfer; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__mem_done() { return (uint8_t*) &top->testbench__DOT__uut__DOT__mem_done; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_lui() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_lui; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_auipc() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_auipc; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_jal() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_jal; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_jalr() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_jalr; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_beq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_beq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_bne() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_bne; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_blt() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_blt; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_bge() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_bge; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_bltu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_bltu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_bgeu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_bgeu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_lb() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_lb; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_lh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_lh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_lw() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_lw; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_lbu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_lbu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_lhu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_lhu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sb() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sb; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sw() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sw; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_addi() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_addi; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_slti() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_slti; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sltiu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sltiu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_xori() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_xori; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_ori() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_ori; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_andi() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_andi; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_slli() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_slli; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_srli() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_srli; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_srai() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_srai; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_add() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_add; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sub() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sub; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sll() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sll; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_slt() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_slt; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sltu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sltu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_xor() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_xor; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_srl() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_srl; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_sra() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_sra; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_or() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_or; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_and() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_and; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_rdcycle() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_rdcycle; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_rdcycleh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_rdcycleh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_rdinstr() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_rdinstr; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_rdinstrh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_rdinstrh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_ecall_ebreak() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_ecall_ebreak; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_getq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_getq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_setq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_setq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_retirq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_retirq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_maskirq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_maskirq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_waitirq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_waitirq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_timer() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_timer; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__instr_trap() { return (uint8_t*) &top->testbench__DOT__uut__DOT__instr_trap; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__decoded_rd() { return (uint8_t*) &top->testbench__DOT__uut__DOT__decoded_rd; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__decoded_rs1() { return (uint8_t*) &top->testbench__DOT__uut__DOT__decoded_rs1; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__decoded_rs2() { return (uint8_t*) &top->testbench__DOT__uut__DOT__decoded_rs2; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__decoder_trigger() { return (uint8_t*) &top->testbench__DOT__uut__DOT__decoder_trigger; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__decoder_trigger_q() { return (uint8_t*) &top->testbench__DOT__uut__DOT__decoder_trigger_q; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__decoder_pseudo_trigger() { return (uint8_t*) &top->testbench__DOT__uut__DOT__decoder_pseudo_trigger; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__decoder_pseudo_trigger_q() { return (uint8_t*) &top->testbench__DOT__uut__DOT__decoder_pseudo_trigger_q; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__compressed_instr() { return (uint8_t*) &top->testbench__DOT__uut__DOT__compressed_instr; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_lui_auipc_jal() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_lui_auipc_jal; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_lb_lh_lw_lbu_lhu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_lb_lh_lw_lbu_lhu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_slli_srli_srai() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_slli_srli_srai; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_sb_sh_sw() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_sb_sh_sw; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_sll_srl_sra() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_sll_srl_sra; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_slti_blt_slt() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_slti_blt_slt; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_sltiu_bltu_sltu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_sltiu_bltu_sltu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_beq_bne_blt_bge_bltu_bgeu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_beq_bne_blt_bge_bltu_bgeu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_lbu_lhu_lw() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_lbu_lhu_lw; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_alu_reg_imm() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_alu_reg_imm; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_alu_reg_reg() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_alu_reg_reg; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__is_compare() { return (uint8_t*) &top->testbench__DOT__uut__DOT__is_compare; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__dbg_next() { return (uint8_t*) &top->testbench__DOT__uut__DOT__dbg_next; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__launch_next_insn() { return (uint8_t*) &top->testbench__DOT__uut__DOT__launch_next_insn; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__cpu_state() { return (uint8_t*) &top->testbench__DOT__uut__DOT__cpu_state; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__set_mem_do_rinst() { return (uint8_t*) &top->testbench__DOT__uut__DOT__set_mem_do_rinst; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__set_mem_do_rdata() { return (uint8_t*) &top->testbench__DOT__uut__DOT__set_mem_do_rdata; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__set_mem_do_wdata() { return (uint8_t*) &top->testbench__DOT__uut__DOT__set_mem_do_wdata; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_store() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_store; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_stalu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_stalu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_branch() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_branch; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_compr() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_compr; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_is_lu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_is_lu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_is_lh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_is_lh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_is_lb() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_is_lb; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__latched_rd() { return (uint8_t*) &top->testbench__DOT__uut__DOT__latched_rd; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__do_waitirq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__do_waitirq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__alu_out_0() { return (uint8_t*) &top->testbench__DOT__uut__DOT__alu_out_0; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__alu_eq() { return (uint8_t*) &top->testbench__DOT__uut__DOT__alu_eq; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__alu_ltu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__alu_ltu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__alu_lts() { return (uint8_t*) &top->testbench__DOT__uut__DOT__alu_lts; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__cpuregs_write() { return (uint8_t*) &top->testbench__DOT__uut__DOT__cpuregs_write; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_resetn_cnt() { return (uint32_t*) &top->testbench__DOT__resetn_cnt; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_mem_addr() { return (uint32_t*) &top->testbench__DOT__mem_addr; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_mem_wdata() { return (uint32_t*) &top->testbench__DOT__mem_wdata; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_mem_rdata() { return (uint32_t*) &top->testbench__DOT__mem_rdata; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_x32() { return (uint32_t*) &top->testbench__DOT__x32; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_next_x32() { return (uint32_t*) &top->testbench__DOT__next_x32; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__mem_la_wdata() { return (uint32_t*) &top->testbench__DOT__uut__DOT__mem_la_wdata; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__pcpi_insn() { return (uint32_t*) &top->testbench__DOT__uut__DOT__pcpi_insn; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__reg_pc() { return (uint32_t*) &top->testbench__DOT__uut__DOT__reg_pc; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__reg_next_pc() { return (uint32_t*) &top->testbench__DOT__uut__DOT__reg_next_pc; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__reg_op1() { return (uint32_t*) &top->testbench__DOT__uut__DOT__reg_op1; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__reg_op2() { return (uint32_t*) &top->testbench__DOT__uut__DOT__reg_op2; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__reg_out() { return (uint32_t*) &top->testbench__DOT__uut__DOT__reg_out; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__next_insn_opcode() { return (uint32_t*) &top->testbench__DOT__uut__DOT__next_insn_opcode; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__dbg_insn_opcode() { return (uint32_t*) &top->testbench__DOT__uut__DOT__dbg_insn_opcode; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__dbg_insn_addr() { return (uint32_t*) &top->testbench__DOT__uut__DOT__dbg_insn_addr; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__next_pc() { return (uint32_t*) &top->testbench__DOT__uut__DOT__next_pc; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__timer() { return (uint32_t*) &top->testbench__DOT__uut__DOT__timer; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__pcpi_mul_rd() { return (uint32_t*) &top->testbench__DOT__uut__DOT__pcpi_mul_rd; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__pcpi_int_rd() { return (uint32_t*) &top->testbench__DOT__uut__DOT__pcpi_int_rd; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__mem_rdata_word() { return (uint32_t*) &top->testbench__DOT__uut__DOT__mem_rdata_word; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__mem_rdata_q() { return (uint32_t*) &top->testbench__DOT__uut__DOT__mem_rdata_q; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__mem_rdata_latched_noshuffle() { return (uint32_t*) &top->testbench__DOT__uut__DOT__mem_rdata_latched_noshuffle; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__decoded_imm() { return (uint32_t*) &top->testbench__DOT__uut__DOT__decoded_imm; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__decoded_imm_j() { return (uint32_t*) &top->testbench__DOT__uut__DOT__decoded_imm_j; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__q_insn_opcode() { return (uint32_t*) &top->testbench__DOT__uut__DOT__q_insn_opcode; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__cached_insn_opcode() { return (uint32_t*) &top->testbench__DOT__uut__DOT__cached_insn_opcode; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__current_pc() { return (uint32_t*) &top->testbench__DOT__uut__DOT__current_pc; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__alu_out() { return (uint32_t*) &top->testbench__DOT__uut__DOT__alu_out; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__alu_out_q() { return (uint32_t*) &top->testbench__DOT__uut__DOT__alu_out_q; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__cpuregs_wrdata() { return (uint32_t*) &top->testbench__DOT__uut__DOT__cpuregs_wrdata; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__cpuregs_rs1() { return (uint32_t*) &top->testbench__DOT__uut__DOT__cpuregs_rs1; }

/** Returns pointer of uint32_t */
uint32_t *get_pointer_uut__DOT__cpuregs_rs2() { return (uint32_t*) &top->testbench__DOT__uut__DOT__cpuregs_rs2; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__new_ascii_instr() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__new_ascii_instr; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__dbg_ascii_instr() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__dbg_ascii_instr; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__q_ascii_instr() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__q_ascii_instr; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__cached_ascii_instr() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__cached_ascii_instr; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx; }

/** Returns pointer of unsigned long int */
unsigned long int *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt() { return (unsigned long int*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt; }

/** Returns pointer of uint8_t array with length 512 */
uint8_t *get_pointer_memory() { return (uint8_t*) top->testbench__DOT__memory; }

/** Returns pointer of uint32_t array with length 32 */
uint32_t *get_pointer_uut__DOT__cpuregs() { return (uint32_t*) top->testbench__DOT__uut__DOT__cpuregs; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1; }

/** Returns pointer of uint8_t */
uint8_t *get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2() { return (uint8_t*) &top->testbench__DOT__uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2; }

buffer_write_t buffer_write_callback;
void buffer_write(int character) { buffer_write_callback(character); }
void set_buffer_write_callback(buffer_write_t function) { buffer_write_callback = function; }
