/**
  * Generated by bindgen.py
  * Date: 2020-05-19 21:29:05.068464
  *
  * Usage in your own code:
  * --------------------------------------------------
  * import bindings from "./bindings";
  *
  * let library = new Library('libVtestbench.dylib',
  *    {
  *      'example_function': ['void', []],
  *      ...bindings.function_definitions
  *    });
  *
  * bindings.setPointers(library);
  * library.example_function();
  *
  */

import ref from "ref-napi";
import {Callback} from "ffi-napi";
const ArrayType = require('ref-array-di')(ref);

export class Bindings {
  private bufferWriteCallbacks = [];
  private bufferWriteCallback = Callback('void', ['int'], (character) => this.callBufferWriteCallbacks(character));
  private callBufferWriteCallbacks(character) {
    for (let callback of this.bufferWriteCallbacks) {
      callback(character);
    }
  }
  public addBufferWriteCallback(fun) {
    this.bufferWriteCallbacks.push(fun);
  }

  private resetn__pointer = ref.alloc('uint8');
  get resetn() {
    // @ts-ignore
    return this.resetn__pointer.deref(); }
  set resetn(value) { this.resetn__pointer.writeUInt8(value, 0); }

  private trap__pointer = ref.alloc('uint8');
  get trap() {
    // @ts-ignore
    return this.trap__pointer.deref(); }
  set trap(value) { this.trap__pointer.writeUInt8(value, 0); }

  private mem_valid__pointer = ref.alloc('uint8');
  get mem_valid() {
    // @ts-ignore
    return this.mem_valid__pointer.deref(); }
  set mem_valid(value) { this.mem_valid__pointer.writeUInt8(value, 0); }

  private mem_ready__pointer = ref.alloc('uint8');
  get mem_ready() {
    // @ts-ignore
    return this.mem_ready__pointer.deref(); }
  set mem_ready(value) { this.mem_ready__pointer.writeUInt8(value, 0); }

  private mem_wstrb__pointer = ref.alloc('uint8');
  get mem_wstrb() {
    // @ts-ignore
    return this.mem_wstrb__pointer.deref(); }
  set mem_wstrb(value) { this.mem_wstrb__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_la_read__pointer = ref.alloc('uint8');
  get uut__DOT__mem_la_read() {
    // @ts-ignore
    return this.uut__DOT__mem_la_read__pointer.deref(); }
  set uut__DOT__mem_la_read(value) { this.uut__DOT__mem_la_read__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_la_write__pointer = ref.alloc('uint8');
  get uut__DOT__mem_la_write() {
    // @ts-ignore
    return this.uut__DOT__mem_la_write__pointer.deref(); }
  set uut__DOT__mem_la_write(value) { this.uut__DOT__mem_la_write__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_la_wstrb__pointer = ref.alloc('uint8');
  get uut__DOT__mem_la_wstrb() {
    // @ts-ignore
    return this.uut__DOT__mem_la_wstrb__pointer.deref(); }
  set uut__DOT__mem_la_wstrb(value) { this.uut__DOT__mem_la_wstrb__pointer.writeUInt8(value, 0); }

  private uut__DOT__pcpi_valid__pointer = ref.alloc('uint8');
  get uut__DOT__pcpi_valid() {
    // @ts-ignore
    return this.uut__DOT__pcpi_valid__pointer.deref(); }
  set uut__DOT__pcpi_valid(value) { this.uut__DOT__pcpi_valid__pointer.writeUInt8(value, 0); }

  private uut__DOT__reg_sh__pointer = ref.alloc('uint8');
  get uut__DOT__reg_sh() {
    // @ts-ignore
    return this.uut__DOT__reg_sh__pointer.deref(); }
  set uut__DOT__reg_sh(value) { this.uut__DOT__reg_sh__pointer.writeUInt8(value, 0); }

  private uut__DOT__pcpi_mul_wr__pointer = ref.alloc('uint8');
  get uut__DOT__pcpi_mul_wr() {
    // @ts-ignore
    return this.uut__DOT__pcpi_mul_wr__pointer.deref(); }
  set uut__DOT__pcpi_mul_wr(value) { this.uut__DOT__pcpi_mul_wr__pointer.writeUInt8(value, 0); }

  private uut__DOT__pcpi_mul_wait__pointer = ref.alloc('uint8');
  get uut__DOT__pcpi_mul_wait() {
    // @ts-ignore
    return this.uut__DOT__pcpi_mul_wait__pointer.deref(); }
  set uut__DOT__pcpi_mul_wait(value) { this.uut__DOT__pcpi_mul_wait__pointer.writeUInt8(value, 0); }

  private uut__DOT__pcpi_mul_ready__pointer = ref.alloc('uint8');
  get uut__DOT__pcpi_mul_ready() {
    // @ts-ignore
    return this.uut__DOT__pcpi_mul_ready__pointer.deref(); }
  set uut__DOT__pcpi_mul_ready(value) { this.uut__DOT__pcpi_mul_ready__pointer.writeUInt8(value, 0); }

  private uut__DOT__pcpi_int_wr__pointer = ref.alloc('uint8');
  get uut__DOT__pcpi_int_wr() {
    // @ts-ignore
    return this.uut__DOT__pcpi_int_wr__pointer.deref(); }
  set uut__DOT__pcpi_int_wr(value) { this.uut__DOT__pcpi_int_wr__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_state__pointer = ref.alloc('uint8');
  get uut__DOT__mem_state() {
    // @ts-ignore
    return this.uut__DOT__mem_state__pointer.deref(); }
  set uut__DOT__mem_state(value) { this.uut__DOT__mem_state__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_wordsize__pointer = ref.alloc('uint8');
  get uut__DOT__mem_wordsize() {
    // @ts-ignore
    return this.uut__DOT__mem_wordsize__pointer.deref(); }
  set uut__DOT__mem_wordsize(value) { this.uut__DOT__mem_wordsize__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_do_prefetch__pointer = ref.alloc('uint8');
  get uut__DOT__mem_do_prefetch() {
    // @ts-ignore
    return this.uut__DOT__mem_do_prefetch__pointer.deref(); }
  set uut__DOT__mem_do_prefetch(value) { this.uut__DOT__mem_do_prefetch__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_do_rinst__pointer = ref.alloc('uint8');
  get uut__DOT__mem_do_rinst() {
    // @ts-ignore
    return this.uut__DOT__mem_do_rinst__pointer.deref(); }
  set uut__DOT__mem_do_rinst(value) { this.uut__DOT__mem_do_rinst__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_do_rdata__pointer = ref.alloc('uint8');
  get uut__DOT__mem_do_rdata() {
    // @ts-ignore
    return this.uut__DOT__mem_do_rdata__pointer.deref(); }
  set uut__DOT__mem_do_rdata(value) { this.uut__DOT__mem_do_rdata__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_do_wdata__pointer = ref.alloc('uint8');
  get uut__DOT__mem_do_wdata() {
    // @ts-ignore
    return this.uut__DOT__mem_do_wdata__pointer.deref(); }
  set uut__DOT__mem_do_wdata(value) { this.uut__DOT__mem_do_wdata__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_xfer__pointer = ref.alloc('uint8');
  get uut__DOT__mem_xfer() {
    // @ts-ignore
    return this.uut__DOT__mem_xfer__pointer.deref(); }
  set uut__DOT__mem_xfer(value) { this.uut__DOT__mem_xfer__pointer.writeUInt8(value, 0); }

  private uut__DOT__mem_done__pointer = ref.alloc('uint8');
  get uut__DOT__mem_done() {
    // @ts-ignore
    return this.uut__DOT__mem_done__pointer.deref(); }
  set uut__DOT__mem_done(value) { this.uut__DOT__mem_done__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_lui__pointer = ref.alloc('uint8');
  get uut__DOT__instr_lui() {
    // @ts-ignore
    return this.uut__DOT__instr_lui__pointer.deref(); }
  set uut__DOT__instr_lui(value) { this.uut__DOT__instr_lui__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_auipc__pointer = ref.alloc('uint8');
  get uut__DOT__instr_auipc() {
    // @ts-ignore
    return this.uut__DOT__instr_auipc__pointer.deref(); }
  set uut__DOT__instr_auipc(value) { this.uut__DOT__instr_auipc__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_jal__pointer = ref.alloc('uint8');
  get uut__DOT__instr_jal() {
    // @ts-ignore
    return this.uut__DOT__instr_jal__pointer.deref(); }
  set uut__DOT__instr_jal(value) { this.uut__DOT__instr_jal__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_jalr__pointer = ref.alloc('uint8');
  get uut__DOT__instr_jalr() {
    // @ts-ignore
    return this.uut__DOT__instr_jalr__pointer.deref(); }
  set uut__DOT__instr_jalr(value) { this.uut__DOT__instr_jalr__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_beq__pointer = ref.alloc('uint8');
  get uut__DOT__instr_beq() {
    // @ts-ignore
    return this.uut__DOT__instr_beq__pointer.deref(); }
  set uut__DOT__instr_beq(value) { this.uut__DOT__instr_beq__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_bne__pointer = ref.alloc('uint8');
  get uut__DOT__instr_bne() {
    // @ts-ignore
    return this.uut__DOT__instr_bne__pointer.deref(); }
  set uut__DOT__instr_bne(value) { this.uut__DOT__instr_bne__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_blt__pointer = ref.alloc('uint8');
  get uut__DOT__instr_blt() {
    // @ts-ignore
    return this.uut__DOT__instr_blt__pointer.deref(); }
  set uut__DOT__instr_blt(value) { this.uut__DOT__instr_blt__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_bge__pointer = ref.alloc('uint8');
  get uut__DOT__instr_bge() {
    // @ts-ignore
    return this.uut__DOT__instr_bge__pointer.deref(); }
  set uut__DOT__instr_bge(value) { this.uut__DOT__instr_bge__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_bltu__pointer = ref.alloc('uint8');
  get uut__DOT__instr_bltu() {
    // @ts-ignore
    return this.uut__DOT__instr_bltu__pointer.deref(); }
  set uut__DOT__instr_bltu(value) { this.uut__DOT__instr_bltu__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_bgeu__pointer = ref.alloc('uint8');
  get uut__DOT__instr_bgeu() {
    // @ts-ignore
    return this.uut__DOT__instr_bgeu__pointer.deref(); }
  set uut__DOT__instr_bgeu(value) { this.uut__DOT__instr_bgeu__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_lb__pointer = ref.alloc('uint8');
  get uut__DOT__instr_lb() {
    // @ts-ignore
    return this.uut__DOT__instr_lb__pointer.deref(); }
  set uut__DOT__instr_lb(value) { this.uut__DOT__instr_lb__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_lh__pointer = ref.alloc('uint8');
  get uut__DOT__instr_lh() {
    // @ts-ignore
    return this.uut__DOT__instr_lh__pointer.deref(); }
  set uut__DOT__instr_lh(value) { this.uut__DOT__instr_lh__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_lw__pointer = ref.alloc('uint8');
  get uut__DOT__instr_lw() {
    // @ts-ignore
    return this.uut__DOT__instr_lw__pointer.deref(); }
  set uut__DOT__instr_lw(value) { this.uut__DOT__instr_lw__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_lbu__pointer = ref.alloc('uint8');
  get uut__DOT__instr_lbu() {
    // @ts-ignore
    return this.uut__DOT__instr_lbu__pointer.deref(); }
  set uut__DOT__instr_lbu(value) { this.uut__DOT__instr_lbu__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_lhu__pointer = ref.alloc('uint8');
  get uut__DOT__instr_lhu() {
    // @ts-ignore
    return this.uut__DOT__instr_lhu__pointer.deref(); }
  set uut__DOT__instr_lhu(value) { this.uut__DOT__instr_lhu__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sb__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sb() {
    // @ts-ignore
    return this.uut__DOT__instr_sb__pointer.deref(); }
  set uut__DOT__instr_sb(value) { this.uut__DOT__instr_sb__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sh__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sh() {
    // @ts-ignore
    return this.uut__DOT__instr_sh__pointer.deref(); }
  set uut__DOT__instr_sh(value) { this.uut__DOT__instr_sh__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sw__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sw() {
    // @ts-ignore
    return this.uut__DOT__instr_sw__pointer.deref(); }
  set uut__DOT__instr_sw(value) { this.uut__DOT__instr_sw__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_addi__pointer = ref.alloc('uint8');
  get uut__DOT__instr_addi() {
    // @ts-ignore
    return this.uut__DOT__instr_addi__pointer.deref(); }
  set uut__DOT__instr_addi(value) { this.uut__DOT__instr_addi__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_slti__pointer = ref.alloc('uint8');
  get uut__DOT__instr_slti() {
    // @ts-ignore
    return this.uut__DOT__instr_slti__pointer.deref(); }
  set uut__DOT__instr_slti(value) { this.uut__DOT__instr_slti__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sltiu__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sltiu() {
    // @ts-ignore
    return this.uut__DOT__instr_sltiu__pointer.deref(); }
  set uut__DOT__instr_sltiu(value) { this.uut__DOT__instr_sltiu__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_xori__pointer = ref.alloc('uint8');
  get uut__DOT__instr_xori() {
    // @ts-ignore
    return this.uut__DOT__instr_xori__pointer.deref(); }
  set uut__DOT__instr_xori(value) { this.uut__DOT__instr_xori__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_ori__pointer = ref.alloc('uint8');
  get uut__DOT__instr_ori() {
    // @ts-ignore
    return this.uut__DOT__instr_ori__pointer.deref(); }
  set uut__DOT__instr_ori(value) { this.uut__DOT__instr_ori__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_andi__pointer = ref.alloc('uint8');
  get uut__DOT__instr_andi() {
    // @ts-ignore
    return this.uut__DOT__instr_andi__pointer.deref(); }
  set uut__DOT__instr_andi(value) { this.uut__DOT__instr_andi__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_slli__pointer = ref.alloc('uint8');
  get uut__DOT__instr_slli() {
    // @ts-ignore
    return this.uut__DOT__instr_slli__pointer.deref(); }
  set uut__DOT__instr_slli(value) { this.uut__DOT__instr_slli__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_srli__pointer = ref.alloc('uint8');
  get uut__DOT__instr_srli() {
    // @ts-ignore
    return this.uut__DOT__instr_srli__pointer.deref(); }
  set uut__DOT__instr_srli(value) { this.uut__DOT__instr_srli__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_srai__pointer = ref.alloc('uint8');
  get uut__DOT__instr_srai() {
    // @ts-ignore
    return this.uut__DOT__instr_srai__pointer.deref(); }
  set uut__DOT__instr_srai(value) { this.uut__DOT__instr_srai__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_add__pointer = ref.alloc('uint8');
  get uut__DOT__instr_add() {
    // @ts-ignore
    return this.uut__DOT__instr_add__pointer.deref(); }
  set uut__DOT__instr_add(value) { this.uut__DOT__instr_add__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sub__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sub() {
    // @ts-ignore
    return this.uut__DOT__instr_sub__pointer.deref(); }
  set uut__DOT__instr_sub(value) { this.uut__DOT__instr_sub__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sll__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sll() {
    // @ts-ignore
    return this.uut__DOT__instr_sll__pointer.deref(); }
  set uut__DOT__instr_sll(value) { this.uut__DOT__instr_sll__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_slt__pointer = ref.alloc('uint8');
  get uut__DOT__instr_slt() {
    // @ts-ignore
    return this.uut__DOT__instr_slt__pointer.deref(); }
  set uut__DOT__instr_slt(value) { this.uut__DOT__instr_slt__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sltu__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sltu() {
    // @ts-ignore
    return this.uut__DOT__instr_sltu__pointer.deref(); }
  set uut__DOT__instr_sltu(value) { this.uut__DOT__instr_sltu__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_xor__pointer = ref.alloc('uint8');
  get uut__DOT__instr_xor() {
    // @ts-ignore
    return this.uut__DOT__instr_xor__pointer.deref(); }
  set uut__DOT__instr_xor(value) { this.uut__DOT__instr_xor__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_srl__pointer = ref.alloc('uint8');
  get uut__DOT__instr_srl() {
    // @ts-ignore
    return this.uut__DOT__instr_srl__pointer.deref(); }
  set uut__DOT__instr_srl(value) { this.uut__DOT__instr_srl__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_sra__pointer = ref.alloc('uint8');
  get uut__DOT__instr_sra() {
    // @ts-ignore
    return this.uut__DOT__instr_sra__pointer.deref(); }
  set uut__DOT__instr_sra(value) { this.uut__DOT__instr_sra__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_or__pointer = ref.alloc('uint8');
  get uut__DOT__instr_or() {
    // @ts-ignore
    return this.uut__DOT__instr_or__pointer.deref(); }
  set uut__DOT__instr_or(value) { this.uut__DOT__instr_or__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_and__pointer = ref.alloc('uint8');
  get uut__DOT__instr_and() {
    // @ts-ignore
    return this.uut__DOT__instr_and__pointer.deref(); }
  set uut__DOT__instr_and(value) { this.uut__DOT__instr_and__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_rdcycle__pointer = ref.alloc('uint8');
  get uut__DOT__instr_rdcycle() {
    // @ts-ignore
    return this.uut__DOT__instr_rdcycle__pointer.deref(); }
  set uut__DOT__instr_rdcycle(value) { this.uut__DOT__instr_rdcycle__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_rdcycleh__pointer = ref.alloc('uint8');
  get uut__DOT__instr_rdcycleh() {
    // @ts-ignore
    return this.uut__DOT__instr_rdcycleh__pointer.deref(); }
  set uut__DOT__instr_rdcycleh(value) { this.uut__DOT__instr_rdcycleh__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_rdinstr__pointer = ref.alloc('uint8');
  get uut__DOT__instr_rdinstr() {
    // @ts-ignore
    return this.uut__DOT__instr_rdinstr__pointer.deref(); }
  set uut__DOT__instr_rdinstr(value) { this.uut__DOT__instr_rdinstr__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_rdinstrh__pointer = ref.alloc('uint8');
  get uut__DOT__instr_rdinstrh() {
    // @ts-ignore
    return this.uut__DOT__instr_rdinstrh__pointer.deref(); }
  set uut__DOT__instr_rdinstrh(value) { this.uut__DOT__instr_rdinstrh__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_ecall_ebreak__pointer = ref.alloc('uint8');
  get uut__DOT__instr_ecall_ebreak() {
    // @ts-ignore
    return this.uut__DOT__instr_ecall_ebreak__pointer.deref(); }
  set uut__DOT__instr_ecall_ebreak(value) { this.uut__DOT__instr_ecall_ebreak__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_getq__pointer = ref.alloc('uint8');
  get uut__DOT__instr_getq() {
    // @ts-ignore
    return this.uut__DOT__instr_getq__pointer.deref(); }
  set uut__DOT__instr_getq(value) { this.uut__DOT__instr_getq__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_setq__pointer = ref.alloc('uint8');
  get uut__DOT__instr_setq() {
    // @ts-ignore
    return this.uut__DOT__instr_setq__pointer.deref(); }
  set uut__DOT__instr_setq(value) { this.uut__DOT__instr_setq__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_retirq__pointer = ref.alloc('uint8');
  get uut__DOT__instr_retirq() {
    // @ts-ignore
    return this.uut__DOT__instr_retirq__pointer.deref(); }
  set uut__DOT__instr_retirq(value) { this.uut__DOT__instr_retirq__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_maskirq__pointer = ref.alloc('uint8');
  get uut__DOT__instr_maskirq() {
    // @ts-ignore
    return this.uut__DOT__instr_maskirq__pointer.deref(); }
  set uut__DOT__instr_maskirq(value) { this.uut__DOT__instr_maskirq__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_waitirq__pointer = ref.alloc('uint8');
  get uut__DOT__instr_waitirq() {
    // @ts-ignore
    return this.uut__DOT__instr_waitirq__pointer.deref(); }
  set uut__DOT__instr_waitirq(value) { this.uut__DOT__instr_waitirq__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_timer__pointer = ref.alloc('uint8');
  get uut__DOT__instr_timer() {
    // @ts-ignore
    return this.uut__DOT__instr_timer__pointer.deref(); }
  set uut__DOT__instr_timer(value) { this.uut__DOT__instr_timer__pointer.writeUInt8(value, 0); }

  private uut__DOT__instr_trap__pointer = ref.alloc('uint8');
  get uut__DOT__instr_trap() {
    // @ts-ignore
    return this.uut__DOT__instr_trap__pointer.deref(); }
  set uut__DOT__instr_trap(value) { this.uut__DOT__instr_trap__pointer.writeUInt8(value, 0); }

  private uut__DOT__decoded_rd__pointer = ref.alloc('uint8');
  get uut__DOT__decoded_rd() {
    // @ts-ignore
    return this.uut__DOT__decoded_rd__pointer.deref(); }
  set uut__DOT__decoded_rd(value) { this.uut__DOT__decoded_rd__pointer.writeUInt8(value, 0); }

  private uut__DOT__decoded_rs1__pointer = ref.alloc('uint8');
  get uut__DOT__decoded_rs1() {
    // @ts-ignore
    return this.uut__DOT__decoded_rs1__pointer.deref(); }
  set uut__DOT__decoded_rs1(value) { this.uut__DOT__decoded_rs1__pointer.writeUInt8(value, 0); }

  private uut__DOT__decoded_rs2__pointer = ref.alloc('uint8');
  get uut__DOT__decoded_rs2() {
    // @ts-ignore
    return this.uut__DOT__decoded_rs2__pointer.deref(); }
  set uut__DOT__decoded_rs2(value) { this.uut__DOT__decoded_rs2__pointer.writeUInt8(value, 0); }

  private uut__DOT__decoder_trigger__pointer = ref.alloc('uint8');
  get uut__DOT__decoder_trigger() {
    // @ts-ignore
    return this.uut__DOT__decoder_trigger__pointer.deref(); }
  set uut__DOT__decoder_trigger(value) { this.uut__DOT__decoder_trigger__pointer.writeUInt8(value, 0); }

  private uut__DOT__decoder_trigger_q__pointer = ref.alloc('uint8');
  get uut__DOT__decoder_trigger_q() {
    // @ts-ignore
    return this.uut__DOT__decoder_trigger_q__pointer.deref(); }
  set uut__DOT__decoder_trigger_q(value) { this.uut__DOT__decoder_trigger_q__pointer.writeUInt8(value, 0); }

  private uut__DOT__decoder_pseudo_trigger__pointer = ref.alloc('uint8');
  get uut__DOT__decoder_pseudo_trigger() {
    // @ts-ignore
    return this.uut__DOT__decoder_pseudo_trigger__pointer.deref(); }
  set uut__DOT__decoder_pseudo_trigger(value) { this.uut__DOT__decoder_pseudo_trigger__pointer.writeUInt8(value, 0); }

  private uut__DOT__decoder_pseudo_trigger_q__pointer = ref.alloc('uint8');
  get uut__DOT__decoder_pseudo_trigger_q() {
    // @ts-ignore
    return this.uut__DOT__decoder_pseudo_trigger_q__pointer.deref(); }
  set uut__DOT__decoder_pseudo_trigger_q(value) { this.uut__DOT__decoder_pseudo_trigger_q__pointer.writeUInt8(value, 0); }

  private uut__DOT__compressed_instr__pointer = ref.alloc('uint8');
  get uut__DOT__compressed_instr() {
    // @ts-ignore
    return this.uut__DOT__compressed_instr__pointer.deref(); }
  set uut__DOT__compressed_instr(value) { this.uut__DOT__compressed_instr__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_lui_auipc_jal__pointer = ref.alloc('uint8');
  get uut__DOT__is_lui_auipc_jal() {
    // @ts-ignore
    return this.uut__DOT__is_lui_auipc_jal__pointer.deref(); }
  set uut__DOT__is_lui_auipc_jal(value) { this.uut__DOT__is_lui_auipc_jal__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_lb_lh_lw_lbu_lhu__pointer = ref.alloc('uint8');
  get uut__DOT__is_lb_lh_lw_lbu_lhu() {
    // @ts-ignore
    return this.uut__DOT__is_lb_lh_lw_lbu_lhu__pointer.deref(); }
  set uut__DOT__is_lb_lh_lw_lbu_lhu(value) { this.uut__DOT__is_lb_lh_lw_lbu_lhu__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_slli_srli_srai__pointer = ref.alloc('uint8');
  get uut__DOT__is_slli_srli_srai() {
    // @ts-ignore
    return this.uut__DOT__is_slli_srli_srai__pointer.deref(); }
  set uut__DOT__is_slli_srli_srai(value) { this.uut__DOT__is_slli_srli_srai__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi__pointer = ref.alloc('uint8');
  get uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi() {
    // @ts-ignore
    return this.uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi__pointer.deref(); }
  set uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi(value) { this.uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_sb_sh_sw__pointer = ref.alloc('uint8');
  get uut__DOT__is_sb_sh_sw() {
    // @ts-ignore
    return this.uut__DOT__is_sb_sh_sw__pointer.deref(); }
  set uut__DOT__is_sb_sh_sw(value) { this.uut__DOT__is_sb_sh_sw__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_sll_srl_sra__pointer = ref.alloc('uint8');
  get uut__DOT__is_sll_srl_sra() {
    // @ts-ignore
    return this.uut__DOT__is_sll_srl_sra__pointer.deref(); }
  set uut__DOT__is_sll_srl_sra(value) { this.uut__DOT__is_sll_srl_sra__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub__pointer = ref.alloc('uint8');
  get uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub() {
    // @ts-ignore
    return this.uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub__pointer.deref(); }
  set uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub(value) { this.uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_slti_blt_slt__pointer = ref.alloc('uint8');
  get uut__DOT__is_slti_blt_slt() {
    // @ts-ignore
    return this.uut__DOT__is_slti_blt_slt__pointer.deref(); }
  set uut__DOT__is_slti_blt_slt(value) { this.uut__DOT__is_slti_blt_slt__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_sltiu_bltu_sltu__pointer = ref.alloc('uint8');
  get uut__DOT__is_sltiu_bltu_sltu() {
    // @ts-ignore
    return this.uut__DOT__is_sltiu_bltu_sltu__pointer.deref(); }
  set uut__DOT__is_sltiu_bltu_sltu(value) { this.uut__DOT__is_sltiu_bltu_sltu__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_beq_bne_blt_bge_bltu_bgeu__pointer = ref.alloc('uint8');
  get uut__DOT__is_beq_bne_blt_bge_bltu_bgeu() {
    // @ts-ignore
    return this.uut__DOT__is_beq_bne_blt_bge_bltu_bgeu__pointer.deref(); }
  set uut__DOT__is_beq_bne_blt_bge_bltu_bgeu(value) { this.uut__DOT__is_beq_bne_blt_bge_bltu_bgeu__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_lbu_lhu_lw__pointer = ref.alloc('uint8');
  get uut__DOT__is_lbu_lhu_lw() {
    // @ts-ignore
    return this.uut__DOT__is_lbu_lhu_lw__pointer.deref(); }
  set uut__DOT__is_lbu_lhu_lw(value) { this.uut__DOT__is_lbu_lhu_lw__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_alu_reg_imm__pointer = ref.alloc('uint8');
  get uut__DOT__is_alu_reg_imm() {
    // @ts-ignore
    return this.uut__DOT__is_alu_reg_imm__pointer.deref(); }
  set uut__DOT__is_alu_reg_imm(value) { this.uut__DOT__is_alu_reg_imm__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_alu_reg_reg__pointer = ref.alloc('uint8');
  get uut__DOT__is_alu_reg_reg() {
    // @ts-ignore
    return this.uut__DOT__is_alu_reg_reg__pointer.deref(); }
  set uut__DOT__is_alu_reg_reg(value) { this.uut__DOT__is_alu_reg_reg__pointer.writeUInt8(value, 0); }

  private uut__DOT__is_compare__pointer = ref.alloc('uint8');
  get uut__DOT__is_compare() {
    // @ts-ignore
    return this.uut__DOT__is_compare__pointer.deref(); }
  set uut__DOT__is_compare(value) { this.uut__DOT__is_compare__pointer.writeUInt8(value, 0); }

  private uut__DOT__cpu_state__pointer = ref.alloc('uint8');
  get uut__DOT__cpu_state() {
    // @ts-ignore
    return this.uut__DOT__cpu_state__pointer.deref(); }
  set uut__DOT__cpu_state(value) { this.uut__DOT__cpu_state__pointer.writeUInt8(value, 0); }

  private uut__DOT__set_mem_do_rinst__pointer = ref.alloc('uint8');
  get uut__DOT__set_mem_do_rinst() {
    // @ts-ignore
    return this.uut__DOT__set_mem_do_rinst__pointer.deref(); }
  set uut__DOT__set_mem_do_rinst(value) { this.uut__DOT__set_mem_do_rinst__pointer.writeUInt8(value, 0); }

  private uut__DOT__set_mem_do_rdata__pointer = ref.alloc('uint8');
  get uut__DOT__set_mem_do_rdata() {
    // @ts-ignore
    return this.uut__DOT__set_mem_do_rdata__pointer.deref(); }
  set uut__DOT__set_mem_do_rdata(value) { this.uut__DOT__set_mem_do_rdata__pointer.writeUInt8(value, 0); }

  private uut__DOT__set_mem_do_wdata__pointer = ref.alloc('uint8');
  get uut__DOT__set_mem_do_wdata() {
    // @ts-ignore
    return this.uut__DOT__set_mem_do_wdata__pointer.deref(); }
  set uut__DOT__set_mem_do_wdata(value) { this.uut__DOT__set_mem_do_wdata__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_store__pointer = ref.alloc('uint8');
  get uut__DOT__latched_store() {
    // @ts-ignore
    return this.uut__DOT__latched_store__pointer.deref(); }
  set uut__DOT__latched_store(value) { this.uut__DOT__latched_store__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_stalu__pointer = ref.alloc('uint8');
  get uut__DOT__latched_stalu() {
    // @ts-ignore
    return this.uut__DOT__latched_stalu__pointer.deref(); }
  set uut__DOT__latched_stalu(value) { this.uut__DOT__latched_stalu__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_branch__pointer = ref.alloc('uint8');
  get uut__DOT__latched_branch() {
    // @ts-ignore
    return this.uut__DOT__latched_branch__pointer.deref(); }
  set uut__DOT__latched_branch(value) { this.uut__DOT__latched_branch__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_compr__pointer = ref.alloc('uint8');
  get uut__DOT__latched_compr() {
    // @ts-ignore
    return this.uut__DOT__latched_compr__pointer.deref(); }
  set uut__DOT__latched_compr(value) { this.uut__DOT__latched_compr__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_is_lu__pointer = ref.alloc('uint8');
  get uut__DOT__latched_is_lu() {
    // @ts-ignore
    return this.uut__DOT__latched_is_lu__pointer.deref(); }
  set uut__DOT__latched_is_lu(value) { this.uut__DOT__latched_is_lu__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_is_lh__pointer = ref.alloc('uint8');
  get uut__DOT__latched_is_lh() {
    // @ts-ignore
    return this.uut__DOT__latched_is_lh__pointer.deref(); }
  set uut__DOT__latched_is_lh(value) { this.uut__DOT__latched_is_lh__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_is_lb__pointer = ref.alloc('uint8');
  get uut__DOT__latched_is_lb() {
    // @ts-ignore
    return this.uut__DOT__latched_is_lb__pointer.deref(); }
  set uut__DOT__latched_is_lb(value) { this.uut__DOT__latched_is_lb__pointer.writeUInt8(value, 0); }

  private uut__DOT__latched_rd__pointer = ref.alloc('uint8');
  get uut__DOT__latched_rd() {
    // @ts-ignore
    return this.uut__DOT__latched_rd__pointer.deref(); }
  set uut__DOT__latched_rd(value) { this.uut__DOT__latched_rd__pointer.writeUInt8(value, 0); }

  private uut__DOT__do_waitirq__pointer = ref.alloc('uint8');
  get uut__DOT__do_waitirq() {
    // @ts-ignore
    return this.uut__DOT__do_waitirq__pointer.deref(); }
  set uut__DOT__do_waitirq(value) { this.uut__DOT__do_waitirq__pointer.writeUInt8(value, 0); }

  private uut__DOT__alu_out_0__pointer = ref.alloc('uint8');
  get uut__DOT__alu_out_0() {
    // @ts-ignore
    return this.uut__DOT__alu_out_0__pointer.deref(); }
  set uut__DOT__alu_out_0(value) { this.uut__DOT__alu_out_0__pointer.writeUInt8(value, 0); }

  private uut__DOT__alu_eq__pointer = ref.alloc('uint8');
  get uut__DOT__alu_eq() {
    // @ts-ignore
    return this.uut__DOT__alu_eq__pointer.deref(); }
  set uut__DOT__alu_eq(value) { this.uut__DOT__alu_eq__pointer.writeUInt8(value, 0); }

  private uut__DOT__alu_ltu__pointer = ref.alloc('uint8');
  get uut__DOT__alu_ltu() {
    // @ts-ignore
    return this.uut__DOT__alu_ltu__pointer.deref(); }
  set uut__DOT__alu_ltu(value) { this.uut__DOT__alu_ltu__pointer.writeUInt8(value, 0); }

  private uut__DOT__alu_lts__pointer = ref.alloc('uint8');
  get uut__DOT__alu_lts() {
    // @ts-ignore
    return this.uut__DOT__alu_lts__pointer.deref(); }
  set uut__DOT__alu_lts(value) { this.uut__DOT__alu_lts__pointer.writeUInt8(value, 0); }

  private uut__DOT__cpuregs_write__pointer = ref.alloc('uint8');
  get uut__DOT__cpuregs_write() {
    // @ts-ignore
    return this.uut__DOT__cpuregs_write__pointer.deref(); }
  set uut__DOT__cpuregs_write(value) { this.uut__DOT__cpuregs_write__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish__pointer.writeUInt8(value, 0); }

  private resetn_cnt__pointer = ref.alloc('uint32');
  get resetn_cnt() {
    // @ts-ignore
    return this.resetn_cnt__pointer.deref(); }
  set resetn_cnt(value) { this.resetn_cnt__pointer.writeUInt32LE(value, 0); }

  private mem_addr__pointer = ref.alloc('uint32');
  get mem_addr() {
    // @ts-ignore
    return this.mem_addr__pointer.deref(); }
  set mem_addr(value) { this.mem_addr__pointer.writeUInt32LE(value, 0); }

  private mem_wdata__pointer = ref.alloc('uint32');
  get mem_wdata() {
    // @ts-ignore
    return this.mem_wdata__pointer.deref(); }
  set mem_wdata(value) { this.mem_wdata__pointer.writeUInt32LE(value, 0); }

  private mem_rdata__pointer = ref.alloc('uint32');
  get mem_rdata() {
    // @ts-ignore
    return this.mem_rdata__pointer.deref(); }
  set mem_rdata(value) { this.mem_rdata__pointer.writeUInt32LE(value, 0); }

  private x32__pointer = ref.alloc('uint32');
  get x32() {
    // @ts-ignore
    return this.x32__pointer.deref(); }
  set x32(value) { this.x32__pointer.writeUInt32LE(value, 0); }

  private next_x32__pointer = ref.alloc('uint32');
  get next_x32() {
    // @ts-ignore
    return this.next_x32__pointer.deref(); }
  set next_x32(value) { this.next_x32__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__mem_la_wdata__pointer = ref.alloc('uint32');
  get uut__DOT__mem_la_wdata() {
    // @ts-ignore
    return this.uut__DOT__mem_la_wdata__pointer.deref(); }
  set uut__DOT__mem_la_wdata(value) { this.uut__DOT__mem_la_wdata__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__pcpi_insn__pointer = ref.alloc('uint32');
  get uut__DOT__pcpi_insn() {
    // @ts-ignore
    return this.uut__DOT__pcpi_insn__pointer.deref(); }
  set uut__DOT__pcpi_insn(value) { this.uut__DOT__pcpi_insn__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__reg_pc__pointer = ref.alloc('uint32');
  get uut__DOT__reg_pc() {
    // @ts-ignore
    return this.uut__DOT__reg_pc__pointer.deref(); }
  set uut__DOT__reg_pc(value) { this.uut__DOT__reg_pc__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__reg_next_pc__pointer = ref.alloc('uint32');
  get uut__DOT__reg_next_pc() {
    // @ts-ignore
    return this.uut__DOT__reg_next_pc__pointer.deref(); }
  set uut__DOT__reg_next_pc(value) { this.uut__DOT__reg_next_pc__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__reg_op1__pointer = ref.alloc('uint32');
  get uut__DOT__reg_op1() {
    // @ts-ignore
    return this.uut__DOT__reg_op1__pointer.deref(); }
  set uut__DOT__reg_op1(value) { this.uut__DOT__reg_op1__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__reg_op2__pointer = ref.alloc('uint32');
  get uut__DOT__reg_op2() {
    // @ts-ignore
    return this.uut__DOT__reg_op2__pointer.deref(); }
  set uut__DOT__reg_op2(value) { this.uut__DOT__reg_op2__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__reg_out__pointer = ref.alloc('uint32');
  get uut__DOT__reg_out() {
    // @ts-ignore
    return this.uut__DOT__reg_out__pointer.deref(); }
  set uut__DOT__reg_out(value) { this.uut__DOT__reg_out__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__next_pc__pointer = ref.alloc('uint32');
  get uut__DOT__next_pc() {
    // @ts-ignore
    return this.uut__DOT__next_pc__pointer.deref(); }
  set uut__DOT__next_pc(value) { this.uut__DOT__next_pc__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__timer__pointer = ref.alloc('uint32');
  get uut__DOT__timer() {
    // @ts-ignore
    return this.uut__DOT__timer__pointer.deref(); }
  set uut__DOT__timer(value) { this.uut__DOT__timer__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__pcpi_mul_rd__pointer = ref.alloc('uint32');
  get uut__DOT__pcpi_mul_rd() {
    // @ts-ignore
    return this.uut__DOT__pcpi_mul_rd__pointer.deref(); }
  set uut__DOT__pcpi_mul_rd(value) { this.uut__DOT__pcpi_mul_rd__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__pcpi_int_rd__pointer = ref.alloc('uint32');
  get uut__DOT__pcpi_int_rd() {
    // @ts-ignore
    return this.uut__DOT__pcpi_int_rd__pointer.deref(); }
  set uut__DOT__pcpi_int_rd(value) { this.uut__DOT__pcpi_int_rd__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__mem_rdata_word__pointer = ref.alloc('uint32');
  get uut__DOT__mem_rdata_word() {
    // @ts-ignore
    return this.uut__DOT__mem_rdata_word__pointer.deref(); }
  set uut__DOT__mem_rdata_word(value) { this.uut__DOT__mem_rdata_word__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__mem_rdata_q__pointer = ref.alloc('uint32');
  get uut__DOT__mem_rdata_q() {
    // @ts-ignore
    return this.uut__DOT__mem_rdata_q__pointer.deref(); }
  set uut__DOT__mem_rdata_q(value) { this.uut__DOT__mem_rdata_q__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__mem_rdata_latched_noshuffle__pointer = ref.alloc('uint32');
  get uut__DOT__mem_rdata_latched_noshuffle() {
    // @ts-ignore
    return this.uut__DOT__mem_rdata_latched_noshuffle__pointer.deref(); }
  set uut__DOT__mem_rdata_latched_noshuffle(value) { this.uut__DOT__mem_rdata_latched_noshuffle__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__decoded_imm__pointer = ref.alloc('uint32');
  get uut__DOT__decoded_imm() {
    // @ts-ignore
    return this.uut__DOT__decoded_imm__pointer.deref(); }
  set uut__DOT__decoded_imm(value) { this.uut__DOT__decoded_imm__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__decoded_imm_j__pointer = ref.alloc('uint32');
  get uut__DOT__decoded_imm_j() {
    // @ts-ignore
    return this.uut__DOT__decoded_imm_j__pointer.deref(); }
  set uut__DOT__decoded_imm_j(value) { this.uut__DOT__decoded_imm_j__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__current_pc__pointer = ref.alloc('uint32');
  get uut__DOT__current_pc() {
    // @ts-ignore
    return this.uut__DOT__current_pc__pointer.deref(); }
  set uut__DOT__current_pc(value) { this.uut__DOT__current_pc__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__alu_out__pointer = ref.alloc('uint32');
  get uut__DOT__alu_out() {
    // @ts-ignore
    return this.uut__DOT__alu_out__pointer.deref(); }
  set uut__DOT__alu_out(value) { this.uut__DOT__alu_out__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__alu_out_q__pointer = ref.alloc('uint32');
  get uut__DOT__alu_out_q() {
    // @ts-ignore
    return this.uut__DOT__alu_out_q__pointer.deref(); }
  set uut__DOT__alu_out_q(value) { this.uut__DOT__alu_out_q__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__cpuregs_wrdata__pointer = ref.alloc('uint32');
  get uut__DOT__cpuregs_wrdata() {
    // @ts-ignore
    return this.uut__DOT__cpuregs_wrdata__pointer.deref(); }
  set uut__DOT__cpuregs_wrdata(value) { this.uut__DOT__cpuregs_wrdata__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__cpuregs_rs1__pointer = ref.alloc('uint32');
  get uut__DOT__cpuregs_rs1() {
    // @ts-ignore
    return this.uut__DOT__cpuregs_rs1__pointer.deref(); }
  set uut__DOT__cpuregs_rs1(value) { this.uut__DOT__cpuregs_rs1__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__cpuregs_rs2__pointer = ref.alloc('uint32');
  get uut__DOT__cpuregs_rs2() {
    // @ts-ignore
    return this.uut__DOT__cpuregs_rs2__pointer.deref(); }
  set uut__DOT__cpuregs_rs2(value) { this.uut__DOT__cpuregs_rs2__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx__pointer.writeUInt32LE(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt__pointer = ref.alloc('ulonglong');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt__pointer.writeUInt32LE(value, 0); }
  public memory = new ArrayType('uint8')(512);
  public uut__DOT__cpuregs = new ArrayType('uint32')(32);

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1__pointer.writeUInt8(value, 0); }

  private uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2__pointer = ref.alloc('uint8');
  get uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2() {
    // @ts-ignore
    return this.uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2__pointer.deref(); }
  set uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2(value) { this.uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2__pointer.writeUInt8(value, 0); }


  public setPointers(library: any) {
    this.resetn__pointer = library.get_pointer_resetn();
    this.trap__pointer = library.get_pointer_trap();
    this.mem_valid__pointer = library.get_pointer_mem_valid();
    this.mem_ready__pointer = library.get_pointer_mem_ready();
    this.mem_wstrb__pointer = library.get_pointer_mem_wstrb();
    this.uut__DOT__mem_la_read__pointer = library.get_pointer_uut__DOT__mem_la_read();
    this.uut__DOT__mem_la_write__pointer = library.get_pointer_uut__DOT__mem_la_write();
    this.uut__DOT__mem_la_wstrb__pointer = library.get_pointer_uut__DOT__mem_la_wstrb();
    this.uut__DOT__pcpi_valid__pointer = library.get_pointer_uut__DOT__pcpi_valid();
    this.uut__DOT__reg_sh__pointer = library.get_pointer_uut__DOT__reg_sh();
    this.uut__DOT__pcpi_mul_wr__pointer = library.get_pointer_uut__DOT__pcpi_mul_wr();
    this.uut__DOT__pcpi_mul_wait__pointer = library.get_pointer_uut__DOT__pcpi_mul_wait();
    this.uut__DOT__pcpi_mul_ready__pointer = library.get_pointer_uut__DOT__pcpi_mul_ready();
    this.uut__DOT__pcpi_int_wr__pointer = library.get_pointer_uut__DOT__pcpi_int_wr();
    this.uut__DOT__mem_state__pointer = library.get_pointer_uut__DOT__mem_state();
    this.uut__DOT__mem_wordsize__pointer = library.get_pointer_uut__DOT__mem_wordsize();
    this.uut__DOT__mem_do_prefetch__pointer = library.get_pointer_uut__DOT__mem_do_prefetch();
    this.uut__DOT__mem_do_rinst__pointer = library.get_pointer_uut__DOT__mem_do_rinst();
    this.uut__DOT__mem_do_rdata__pointer = library.get_pointer_uut__DOT__mem_do_rdata();
    this.uut__DOT__mem_do_wdata__pointer = library.get_pointer_uut__DOT__mem_do_wdata();
    this.uut__DOT__mem_xfer__pointer = library.get_pointer_uut__DOT__mem_xfer();
    this.uut__DOT__mem_done__pointer = library.get_pointer_uut__DOT__mem_done();
    this.uut__DOT__instr_lui__pointer = library.get_pointer_uut__DOT__instr_lui();
    this.uut__DOT__instr_auipc__pointer = library.get_pointer_uut__DOT__instr_auipc();
    this.uut__DOT__instr_jal__pointer = library.get_pointer_uut__DOT__instr_jal();
    this.uut__DOT__instr_jalr__pointer = library.get_pointer_uut__DOT__instr_jalr();
    this.uut__DOT__instr_beq__pointer = library.get_pointer_uut__DOT__instr_beq();
    this.uut__DOT__instr_bne__pointer = library.get_pointer_uut__DOT__instr_bne();
    this.uut__DOT__instr_blt__pointer = library.get_pointer_uut__DOT__instr_blt();
    this.uut__DOT__instr_bge__pointer = library.get_pointer_uut__DOT__instr_bge();
    this.uut__DOT__instr_bltu__pointer = library.get_pointer_uut__DOT__instr_bltu();
    this.uut__DOT__instr_bgeu__pointer = library.get_pointer_uut__DOT__instr_bgeu();
    this.uut__DOT__instr_lb__pointer = library.get_pointer_uut__DOT__instr_lb();
    this.uut__DOT__instr_lh__pointer = library.get_pointer_uut__DOT__instr_lh();
    this.uut__DOT__instr_lw__pointer = library.get_pointer_uut__DOT__instr_lw();
    this.uut__DOT__instr_lbu__pointer = library.get_pointer_uut__DOT__instr_lbu();
    this.uut__DOT__instr_lhu__pointer = library.get_pointer_uut__DOT__instr_lhu();
    this.uut__DOT__instr_sb__pointer = library.get_pointer_uut__DOT__instr_sb();
    this.uut__DOT__instr_sh__pointer = library.get_pointer_uut__DOT__instr_sh();
    this.uut__DOT__instr_sw__pointer = library.get_pointer_uut__DOT__instr_sw();
    this.uut__DOT__instr_addi__pointer = library.get_pointer_uut__DOT__instr_addi();
    this.uut__DOT__instr_slti__pointer = library.get_pointer_uut__DOT__instr_slti();
    this.uut__DOT__instr_sltiu__pointer = library.get_pointer_uut__DOT__instr_sltiu();
    this.uut__DOT__instr_xori__pointer = library.get_pointer_uut__DOT__instr_xori();
    this.uut__DOT__instr_ori__pointer = library.get_pointer_uut__DOT__instr_ori();
    this.uut__DOT__instr_andi__pointer = library.get_pointer_uut__DOT__instr_andi();
    this.uut__DOT__instr_slli__pointer = library.get_pointer_uut__DOT__instr_slli();
    this.uut__DOT__instr_srli__pointer = library.get_pointer_uut__DOT__instr_srli();
    this.uut__DOT__instr_srai__pointer = library.get_pointer_uut__DOT__instr_srai();
    this.uut__DOT__instr_add__pointer = library.get_pointer_uut__DOT__instr_add();
    this.uut__DOT__instr_sub__pointer = library.get_pointer_uut__DOT__instr_sub();
    this.uut__DOT__instr_sll__pointer = library.get_pointer_uut__DOT__instr_sll();
    this.uut__DOT__instr_slt__pointer = library.get_pointer_uut__DOT__instr_slt();
    this.uut__DOT__instr_sltu__pointer = library.get_pointer_uut__DOT__instr_sltu();
    this.uut__DOT__instr_xor__pointer = library.get_pointer_uut__DOT__instr_xor();
    this.uut__DOT__instr_srl__pointer = library.get_pointer_uut__DOT__instr_srl();
    this.uut__DOT__instr_sra__pointer = library.get_pointer_uut__DOT__instr_sra();
    this.uut__DOT__instr_or__pointer = library.get_pointer_uut__DOT__instr_or();
    this.uut__DOT__instr_and__pointer = library.get_pointer_uut__DOT__instr_and();
    this.uut__DOT__instr_rdcycle__pointer = library.get_pointer_uut__DOT__instr_rdcycle();
    this.uut__DOT__instr_rdcycleh__pointer = library.get_pointer_uut__DOT__instr_rdcycleh();
    this.uut__DOT__instr_rdinstr__pointer = library.get_pointer_uut__DOT__instr_rdinstr();
    this.uut__DOT__instr_rdinstrh__pointer = library.get_pointer_uut__DOT__instr_rdinstrh();
    this.uut__DOT__instr_ecall_ebreak__pointer = library.get_pointer_uut__DOT__instr_ecall_ebreak();
    this.uut__DOT__instr_getq__pointer = library.get_pointer_uut__DOT__instr_getq();
    this.uut__DOT__instr_setq__pointer = library.get_pointer_uut__DOT__instr_setq();
    this.uut__DOT__instr_retirq__pointer = library.get_pointer_uut__DOT__instr_retirq();
    this.uut__DOT__instr_maskirq__pointer = library.get_pointer_uut__DOT__instr_maskirq();
    this.uut__DOT__instr_waitirq__pointer = library.get_pointer_uut__DOT__instr_waitirq();
    this.uut__DOT__instr_timer__pointer = library.get_pointer_uut__DOT__instr_timer();
    this.uut__DOT__instr_trap__pointer = library.get_pointer_uut__DOT__instr_trap();
    this.uut__DOT__decoded_rd__pointer = library.get_pointer_uut__DOT__decoded_rd();
    this.uut__DOT__decoded_rs1__pointer = library.get_pointer_uut__DOT__decoded_rs1();
    this.uut__DOT__decoded_rs2__pointer = library.get_pointer_uut__DOT__decoded_rs2();
    this.uut__DOT__decoder_trigger__pointer = library.get_pointer_uut__DOT__decoder_trigger();
    this.uut__DOT__decoder_trigger_q__pointer = library.get_pointer_uut__DOT__decoder_trigger_q();
    this.uut__DOT__decoder_pseudo_trigger__pointer = library.get_pointer_uut__DOT__decoder_pseudo_trigger();
    this.uut__DOT__decoder_pseudo_trigger_q__pointer = library.get_pointer_uut__DOT__decoder_pseudo_trigger_q();
    this.uut__DOT__compressed_instr__pointer = library.get_pointer_uut__DOT__compressed_instr();
    this.uut__DOT__is_lui_auipc_jal__pointer = library.get_pointer_uut__DOT__is_lui_auipc_jal();
    this.uut__DOT__is_lb_lh_lw_lbu_lhu__pointer = library.get_pointer_uut__DOT__is_lb_lh_lw_lbu_lhu();
    this.uut__DOT__is_slli_srli_srai__pointer = library.get_pointer_uut__DOT__is_slli_srli_srai();
    this.uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi__pointer = library.get_pointer_uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi();
    this.uut__DOT__is_sb_sh_sw__pointer = library.get_pointer_uut__DOT__is_sb_sh_sw();
    this.uut__DOT__is_sll_srl_sra__pointer = library.get_pointer_uut__DOT__is_sll_srl_sra();
    this.uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub__pointer = library.get_pointer_uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub();
    this.uut__DOT__is_slti_blt_slt__pointer = library.get_pointer_uut__DOT__is_slti_blt_slt();
    this.uut__DOT__is_sltiu_bltu_sltu__pointer = library.get_pointer_uut__DOT__is_sltiu_bltu_sltu();
    this.uut__DOT__is_beq_bne_blt_bge_bltu_bgeu__pointer = library.get_pointer_uut__DOT__is_beq_bne_blt_bge_bltu_bgeu();
    this.uut__DOT__is_lbu_lhu_lw__pointer = library.get_pointer_uut__DOT__is_lbu_lhu_lw();
    this.uut__DOT__is_alu_reg_imm__pointer = library.get_pointer_uut__DOT__is_alu_reg_imm();
    this.uut__DOT__is_alu_reg_reg__pointer = library.get_pointer_uut__DOT__is_alu_reg_reg();
    this.uut__DOT__is_compare__pointer = library.get_pointer_uut__DOT__is_compare();
    this.uut__DOT__cpu_state__pointer = library.get_pointer_uut__DOT__cpu_state();
    this.uut__DOT__set_mem_do_rinst__pointer = library.get_pointer_uut__DOT__set_mem_do_rinst();
    this.uut__DOT__set_mem_do_rdata__pointer = library.get_pointer_uut__DOT__set_mem_do_rdata();
    this.uut__DOT__set_mem_do_wdata__pointer = library.get_pointer_uut__DOT__set_mem_do_wdata();
    this.uut__DOT__latched_store__pointer = library.get_pointer_uut__DOT__latched_store();
    this.uut__DOT__latched_stalu__pointer = library.get_pointer_uut__DOT__latched_stalu();
    this.uut__DOT__latched_branch__pointer = library.get_pointer_uut__DOT__latched_branch();
    this.uut__DOT__latched_compr__pointer = library.get_pointer_uut__DOT__latched_compr();
    this.uut__DOT__latched_is_lu__pointer = library.get_pointer_uut__DOT__latched_is_lu();
    this.uut__DOT__latched_is_lh__pointer = library.get_pointer_uut__DOT__latched_is_lh();
    this.uut__DOT__latched_is_lb__pointer = library.get_pointer_uut__DOT__latched_is_lb();
    this.uut__DOT__latched_rd__pointer = library.get_pointer_uut__DOT__latched_rd();
    this.uut__DOT__do_waitirq__pointer = library.get_pointer_uut__DOT__do_waitirq();
    this.uut__DOT__alu_out_0__pointer = library.get_pointer_uut__DOT__alu_out_0();
    this.uut__DOT__alu_eq__pointer = library.get_pointer_uut__DOT__alu_eq();
    this.uut__DOT__alu_ltu__pointer = library.get_pointer_uut__DOT__alu_ltu();
    this.uut__DOT__alu_lts__pointer = library.get_pointer_uut__DOT__alu_lts();
    this.uut__DOT__cpuregs_write__pointer = library.get_pointer_uut__DOT__cpuregs_write();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish();
    this.resetn_cnt__pointer = library.get_pointer_resetn_cnt();
    this.mem_addr__pointer = library.get_pointer_mem_addr();
    this.mem_wdata__pointer = library.get_pointer_mem_wdata();
    this.mem_rdata__pointer = library.get_pointer_mem_rdata();
    this.x32__pointer = library.get_pointer_x32();
    this.next_x32__pointer = library.get_pointer_next_x32();
    this.uut__DOT__mem_la_wdata__pointer = library.get_pointer_uut__DOT__mem_la_wdata();
    this.uut__DOT__pcpi_insn__pointer = library.get_pointer_uut__DOT__pcpi_insn();
    this.uut__DOT__reg_pc__pointer = library.get_pointer_uut__DOT__reg_pc();
    this.uut__DOT__reg_next_pc__pointer = library.get_pointer_uut__DOT__reg_next_pc();
    this.uut__DOT__reg_op1__pointer = library.get_pointer_uut__DOT__reg_op1();
    this.uut__DOT__reg_op2__pointer = library.get_pointer_uut__DOT__reg_op2();
    this.uut__DOT__reg_out__pointer = library.get_pointer_uut__DOT__reg_out();
    this.uut__DOT__next_pc__pointer = library.get_pointer_uut__DOT__next_pc();
    this.uut__DOT__timer__pointer = library.get_pointer_uut__DOT__timer();
    this.uut__DOT__pcpi_mul_rd__pointer = library.get_pointer_uut__DOT__pcpi_mul_rd();
    this.uut__DOT__pcpi_int_rd__pointer = library.get_pointer_uut__DOT__pcpi_int_rd();
    this.uut__DOT__mem_rdata_word__pointer = library.get_pointer_uut__DOT__mem_rdata_word();
    this.uut__DOT__mem_rdata_q__pointer = library.get_pointer_uut__DOT__mem_rdata_q();
    this.uut__DOT__mem_rdata_latched_noshuffle__pointer = library.get_pointer_uut__DOT__mem_rdata_latched_noshuffle();
    this.uut__DOT__decoded_imm__pointer = library.get_pointer_uut__DOT__decoded_imm();
    this.uut__DOT__decoded_imm_j__pointer = library.get_pointer_uut__DOT__decoded_imm_j();
    this.uut__DOT__current_pc__pointer = library.get_pointer_uut__DOT__current_pc();
    this.uut__DOT__alu_out__pointer = library.get_pointer_uut__DOT__alu_out();
    this.uut__DOT__alu_out_q__pointer = library.get_pointer_uut__DOT__alu_out_q();
    this.uut__DOT__cpuregs_wrdata__pointer = library.get_pointer_uut__DOT__cpuregs_wrdata();
    this.uut__DOT__cpuregs_rs1__pointer = library.get_pointer_uut__DOT__cpuregs_rs1();
    this.uut__DOT__cpuregs_rs2__pointer = library.get_pointer_uut__DOT__cpuregs_rs2();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt();
    this.memory.buffer = library.get_pointer_memory();
    this.uut__DOT__cpuregs.buffer = library.get_pointer_uut__DOT__cpuregs();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1();
    this.uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2__pointer = library.get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2();
    library.set_buffer_write_callback(this.bufferWriteCallback);
    process.on('exit', () => { this.bufferWriteCallback });
  }

  public function_definitions = {
    'get_pointer_resetn': ['uint8 *', []],
    'get_pointer_trap': ['uint8 *', []],
    'get_pointer_mem_valid': ['uint8 *', []],
    'get_pointer_mem_ready': ['uint8 *', []],
    'get_pointer_mem_wstrb': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_la_read': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_la_write': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_la_wstrb': ['uint8 *', []],
    'get_pointer_uut__DOT__pcpi_valid': ['uint8 *', []],
    'get_pointer_uut__DOT__reg_sh': ['uint8 *', []],
    'get_pointer_uut__DOT__pcpi_mul_wr': ['uint8 *', []],
    'get_pointer_uut__DOT__pcpi_mul_wait': ['uint8 *', []],
    'get_pointer_uut__DOT__pcpi_mul_ready': ['uint8 *', []],
    'get_pointer_uut__DOT__pcpi_int_wr': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_state': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_wordsize': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_do_prefetch': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_do_rinst': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_do_rdata': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_do_wdata': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_xfer': ['uint8 *', []],
    'get_pointer_uut__DOT__mem_done': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_lui': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_auipc': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_jal': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_jalr': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_beq': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_bne': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_blt': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_bge': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_bltu': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_bgeu': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_lb': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_lh': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_lw': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_lbu': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_lhu': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sb': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sh': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sw': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_addi': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_slti': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sltiu': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_xori': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_ori': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_andi': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_slli': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_srli': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_srai': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_add': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sub': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sll': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_slt': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sltu': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_xor': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_srl': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_sra': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_or': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_and': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_rdcycle': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_rdcycleh': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_rdinstr': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_rdinstrh': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_ecall_ebreak': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_getq': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_setq': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_retirq': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_maskirq': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_waitirq': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_timer': ['uint8 *', []],
    'get_pointer_uut__DOT__instr_trap': ['uint8 *', []],
    'get_pointer_uut__DOT__decoded_rd': ['uint8 *', []],
    'get_pointer_uut__DOT__decoded_rs1': ['uint8 *', []],
    'get_pointer_uut__DOT__decoded_rs2': ['uint8 *', []],
    'get_pointer_uut__DOT__decoder_trigger': ['uint8 *', []],
    'get_pointer_uut__DOT__decoder_trigger_q': ['uint8 *', []],
    'get_pointer_uut__DOT__decoder_pseudo_trigger': ['uint8 *', []],
    'get_pointer_uut__DOT__decoder_pseudo_trigger_q': ['uint8 *', []],
    'get_pointer_uut__DOT__compressed_instr': ['uint8 *', []],
    'get_pointer_uut__DOT__is_lui_auipc_jal': ['uint8 *', []],
    'get_pointer_uut__DOT__is_lb_lh_lw_lbu_lhu': ['uint8 *', []],
    'get_pointer_uut__DOT__is_slli_srli_srai': ['uint8 *', []],
    'get_pointer_uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi': ['uint8 *', []],
    'get_pointer_uut__DOT__is_sb_sh_sw': ['uint8 *', []],
    'get_pointer_uut__DOT__is_sll_srl_sra': ['uint8 *', []],
    'get_pointer_uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub': ['uint8 *', []],
    'get_pointer_uut__DOT__is_slti_blt_slt': ['uint8 *', []],
    'get_pointer_uut__DOT__is_sltiu_bltu_sltu': ['uint8 *', []],
    'get_pointer_uut__DOT__is_beq_bne_blt_bge_bltu_bgeu': ['uint8 *', []],
    'get_pointer_uut__DOT__is_lbu_lhu_lw': ['uint8 *', []],
    'get_pointer_uut__DOT__is_alu_reg_imm': ['uint8 *', []],
    'get_pointer_uut__DOT__is_alu_reg_reg': ['uint8 *', []],
    'get_pointer_uut__DOT__is_compare': ['uint8 *', []],
    'get_pointer_uut__DOT__cpu_state': ['uint8 *', []],
    'get_pointer_uut__DOT__set_mem_do_rinst': ['uint8 *', []],
    'get_pointer_uut__DOT__set_mem_do_rdata': ['uint8 *', []],
    'get_pointer_uut__DOT__set_mem_do_wdata': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_store': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_stalu': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_branch': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_compr': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_is_lu': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_is_lh': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_is_lb': ['uint8 *', []],
    'get_pointer_uut__DOT__latched_rd': ['uint8 *', []],
    'get_pointer_uut__DOT__do_waitirq': ['uint8 *', []],
    'get_pointer_uut__DOT__alu_out_0': ['uint8 *', []],
    'get_pointer_uut__DOT__alu_eq': ['uint8 *', []],
    'get_pointer_uut__DOT__alu_ltu': ['uint8 *', []],
    'get_pointer_uut__DOT__alu_lts': ['uint8 *', []],
    'get_pointer_uut__DOT__cpuregs_write': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish': ['uint8 *', []],
    'get_pointer_resetn_cnt': ['uint32 *', []],
    'get_pointer_mem_addr': ['uint32 *', []],
    'get_pointer_mem_wdata': ['uint32 *', []],
    'get_pointer_mem_rdata': ['uint32 *', []],
    'get_pointer_x32': ['uint32 *', []],
    'get_pointer_next_x32': ['uint32 *', []],
    'get_pointer_uut__DOT__mem_la_wdata': ['uint32 *', []],
    'get_pointer_uut__DOT__pcpi_insn': ['uint32 *', []],
    'get_pointer_uut__DOT__reg_pc': ['uint32 *', []],
    'get_pointer_uut__DOT__reg_next_pc': ['uint32 *', []],
    'get_pointer_uut__DOT__reg_op1': ['uint32 *', []],
    'get_pointer_uut__DOT__reg_op2': ['uint32 *', []],
    'get_pointer_uut__DOT__reg_out': ['uint32 *', []],
    'get_pointer_uut__DOT__next_pc': ['uint32 *', []],
    'get_pointer_uut__DOT__timer': ['uint32 *', []],
    'get_pointer_uut__DOT__pcpi_mul_rd': ['uint32 *', []],
    'get_pointer_uut__DOT__pcpi_int_rd': ['uint32 *', []],
    'get_pointer_uut__DOT__mem_rdata_word': ['uint32 *', []],
    'get_pointer_uut__DOT__mem_rdata_q': ['uint32 *', []],
    'get_pointer_uut__DOT__mem_rdata_latched_noshuffle': ['uint32 *', []],
    'get_pointer_uut__DOT__decoded_imm': ['uint32 *', []],
    'get_pointer_uut__DOT__decoded_imm_j': ['uint32 *', []],
    'get_pointer_uut__DOT__current_pc': ['uint32 *', []],
    'get_pointer_uut__DOT__alu_out': ['uint32 *', []],
    'get_pointer_uut__DOT__alu_out_q': ['uint32 *', []],
    'get_pointer_uut__DOT__cpuregs_wrdata': ['uint32 *', []],
    'get_pointer_uut__DOT__cpuregs_rs1': ['uint32 *', []],
    'get_pointer_uut__DOT__cpuregs_rs2': ['uint32 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs1': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rs2': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rd': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__rdx': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx': ['ulonglong *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt': ['ulonglong *', []],
    'get_pointer_memory': ['uint8 *', []],
    'get_pointer_uut__DOT__cpuregs': ['uint32 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1': ['uint8 *', []],
    'get_pointer_uut__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2': ['uint8 *', []],
    'set_buffer_write_callback': ['void', ['pointer']]
  }
}
export default new Bindings();
